const Map<String, String> _kCountryFlags = {
  // English names
  'Taiwan': '🇹🇼', 'Japan': '🇯🇵', 'South Korea': '🇰🇷', 'China': '🇨🇳',
  'Hong Kong': '🇭🇰', 'Macau': '🇲🇴', 'Mongolia': '🇲🇳',
  'Thailand': '🇹🇭', 'Vietnam': '🇻🇳', 'Singapore': '🇸🇬',
  'Malaysia': '🇲🇾', 'Indonesia': '🇮🇩', 'Philippines': '🇵🇭',
  'Cambodia': '🇰🇭', 'Myanmar': '🇲🇲',
  'India': '🇮🇳', 'Nepal': '🇳🇵', 'Sri Lanka': '🇱🇰',
  'Maldives': '🇲🇻', 'Bhutan': '🇧🇹',
  'United Kingdom': '🇬🇧', 'France': '🇫🇷', 'Germany': '🇩🇪',
  'Italy': '🇮🇹', 'Spain': '🇪🇸', 'Portugal': '🇵🇹',
  'Netherlands': '🇳🇱', 'Switzerland': '🇨🇭', 'Austria': '🇦🇹',
  'Belgium': '🇧🇪', 'Sweden': '🇸🇪', 'Norway': '🇳🇴',
  'Denmark': '🇩🇰', 'Finland': '🇫🇮', 'Poland': '🇵🇱',
  'Czech Republic': '🇨🇿', 'Hungary': '🇭🇺', 'Greece': '🇬🇷',
  'Croatia': '🇭🇷', 'Iceland': '🇮🇸',
  'United States': '🇺🇸', 'Canada': '🇨🇦', 'Mexico': '🇲🇽',
  'Brazil': '🇧🇷', 'Argentina': '🇦🇷', 'Peru': '🇵🇪',
  'Australia': '🇦🇺', 'New Zealand': '🇳🇿',
  'UAE': '🇦🇪', 'Israel': '🇮🇱',
  'Egypt': '🇪🇬', 'Morocco': '🇲🇦',
  // Chinese names
  '台灣': '🇹🇼', '日本': '🇯🇵', '南韓': '🇰🇷', '中國': '🇨🇳',
  '香港': '🇭🇰', '澳門': '🇲🇴', '蒙古': '🇲🇳',
  '泰國': '🇹🇭', '越南': '🇻🇳', '新加坡': '🇸🇬',
  '馬來西亞': '🇲🇾', '印尼': '🇮🇩', '菲律賓': '🇵🇭',
  '柬埔寨': '🇰🇭', '緬甸': '🇲🇲',
  '印度': '🇮🇳', '尼泊爾': '🇳🇵', '斯里蘭卡': '🇱🇰',
  '馬爾地夫': '🇲🇻', '不丹': '🇧🇹',
  '英國': '🇬🇧', '法國': '🇫🇷', '德國': '🇩🇪',
  '義大利': '🇮🇹', '西班牙': '🇪🇸', '葡萄牙': '🇵🇹',
  '荷蘭': '🇳🇱', '瑞士': '🇨🇭', '奧地利': '🇦🇹',
  '比利時': '🇧🇪', '瑞典': '🇸🇪', '挪威': '🇳🇴',
  '丹麥': '🇩🇰', '芬蘭': '🇫🇮', '波蘭': '🇵🇱',
  '捷克': '🇨🇿', '匈牙利': '🇭🇺', '希臘': '🇬🇷',
  '克羅埃西亞': '🇭🇷', '冰島': '🇮🇸',
  '美國': '🇺🇸', '加拿大': '🇨🇦', '墨西哥': '🇲🇽',
  '巴西': '🇧🇷', '阿根廷': '🇦🇷', '秘魯': '🇵🇪',
  '澳洲': '🇦🇺', '紐西蘭': '🇳🇿',
  '阿聯': '🇦🇪', '以色列': '🇮🇱',
  '埃及': '🇪🇬', '摩洛哥': '🇲🇦',
};

String countryFlag(String country) => _kCountryFlags[country] ?? '🌍';
